@startuml
participant Client
participant Facade
participant SystemA
participant SystemB
participant SystemC
autonumber
Client->Facade:create
activate Facade
Facade->SystemA:create
Facade->SystemB:create
Facade->SystemC:create
deactivate Facade
Client->Facade:wrapOpration()
activate Facade
Facade->SystemA:operationA()
Facade->SystemB:operationB()
Facade->SystemC:operation()
deactivate Facade


@enduml